# Generated by Django 2.0 on 2020-08-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0002_transferhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferhistory',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditapp.User'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_credits', to='creditapp.User'),
        ),
    ]
